image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build

test_script:
  - npm lint && npm test  # скрипт тестирования

deploy_script:  # скрипт развёртывания
  - git config --global user.name "AppVeyor"
  - git config --global user.email "info@appveyor.com"
  - npm install push-dir --save-dev
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
