image: Ubuntu2204  # Use Ubuntu 22.04 as the build environment

stack: node 20  # Node.js 20 environment

branches:
  only:
    - master
    - video
    - main

cache: node_modules  # Cache the node_modules directory for faster builds

install:
  - npm install  # Install project dependencies

build_script:
  - npm run build  # Run your build command (ensure this exists in package.json)

deploy_script:  # Deployment to gh-pages
  - git config --global user.name "AppVeyor"
  - git config --global user.email "info@appveyor.com"
  - npm install push-dir --save-dev
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose
